import { pgTable, uuid, text, timestamp } from "drizzle-orm/pg-core";

/**
 * Profiles table for Neon Auth integration.
 * The id field is linked to Neon Auth's user management system.
 * When a user signs up via Neon Auth, their user_id is stored here.
 */
export const profiles = pgTable("profiles", {
  // Linked to Neon Auth's user_id (UUID generated by Neon Auth)
  id: uuid("id").primaryKey(),
  email: text("email").notNull(),
  username: text("username").notNull().unique(),
  avatarUrl: text("avatar_url"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
});

export type Profile = typeof profiles.$inferSelect;
export type NewProfile = typeof profiles.$inferInsert;
